# Initial Cleaning of the Merged Master Dataset

This notebook performs the first stage of cleaning and inspection for the merged thesis dataset.

It is designed to:
- load the merged dataset
- inspect column names, data types, and general data quality
- review columns in a structured way
- apply only basic and safe cleaning steps
- avoid model-specific preprocessing at this stage

The goal is to make the dataset easier to understand before any later feature engineering, imputation strategy, encoding, or modeling decisions.

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd
from IPython.display import display

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_colwidth", 120)
pd.set_option("display.float_format", lambda value: f"{value:,.3f}")

## Load Dataset

The merged dataset combines price observations with Traficom-based features. A copy of the raw data is kept so that all cleaning steps remain explicit and easy to review.

In [2]:
data_path = Path("/Users/riteshbhandari/Documents/Dokumentit – Ritesh - MacBook Pro/GitHub/DPPM/datasets/merged/price_traficom_merged.csv")

if not data_path.exists():
    raise FileNotFoundError(f"Dataset not found: {data_path}")

df_raw = pd.read_csv(data_path, skipinitialspace=True)
df = df_raw.copy()

print(f"Dataset path: {data_path}")
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]:,}")

display(df.head())

Dataset path: /Users/riteshbhandari/Documents/Dokumentit – Ritesh - MacBook Pro/GitHub/DPPM/datasets/merged/price_traficom_merged.csv
Rows: 11,374
Columns: 70

,product_id,part_name,price,quality_grade,oem_number,mileage,brand,model,category,subcategory,scrape_date,year_start,year_end,year_span,year_mid,brand_merge_key,model_merge_key,repair_status,brand_is_known_model_family,model_looks_like_part_taxonomy,model_family_clean,model_total_registered,model_median_vehicle_age,model_mean_vehicle_age,model_median_mileage,model_mean_mileage,model_median_engine_cc,model_median_power_kw,model_median_mass_kg,model_share_of_market,model_share_within_brand,model_share_over_10y,model_share_over_200k_km,model_automatic_share,model_petrol_share,model_diesel_share,model_ev_share,model_hybrid_share,model_turbo_share,model_firstreg_total_2014_2026,model_firstreg_recent_share,model_firstreg_old_share,model_firstreg_weighted_year,model_firstreg_peak_year,model_firstreg_peak_count,model_firstreg_year_span,brand_total_registered,brand_median_vehicle_age,brand_mean_vehicle_age,brand_median_mileage,brand_mean_mileage,brand_median_engine_cc,brand_median_power_kw,brand_median_mass_kg,brand_share_of_market,brand_share_over_10y,brand_share_over_200k_km,brand_automatic_share,brand_petrol_share,brand_diesel_share,brand_ev_share,brand_hybrid_share,brand_turbo_share,brand_firstreg_total_2014_2026,brand_firstreg_recent_share,brand_firstreg_old_share,brand_firstreg_weighted_year,brand_firstreg_peak_year,brand_firstreg_peak_count,brand_firstreg_year_span
0,"63,136,980.000","Contact roll Airbag - , e-",177.600,A2,FI02042722A,"224,000.000",vw,golf,airbag,contact roll airbag,2026-02-03,2013,2020,7,"2,016.500",volkswagen,golf,original_valid,True,False,golf,86762,13.000,13.749,"186,801.000","195,467.968","1,395.000",81.000,"1,330.000",0.034,0.311,0.652,0.433,0.383,0.786,0.170,0.013,0.068,0.726,"31,860.000",0.170,0.669,"2,017.604","2,014.000","5,265.000",12.000,279311,11.000,12.154,"177,745.000","192,564.366","1,498.000",85.000,"1,400.000",0.109,0.538,0.387,0.478,0.657,0.246,0.075,0.073,0.686,"31,860.000",0.170,0.669,"2,017.604","2,014.000","5,265.000",12.000
1,"64,390,201.000","Contact roll Airbag - , e-",177.600,A2,FI05351686A,"272,000.000",vw,golf,airbag,contact roll airbag,2026-02-03,2013,2020,7,"2,016.500",volkswagen,golf,original_valid,True,False,golf,86762,13.000,13.749,"186,801.000","195,467.968","1,395.000",81.000,"1,330.000",0.034,0.311,0.652,0.433,0.383,0.786,0.170,0.013,0.068,0.726,"31,860.000",0.170,0.669,"2,017.604","2,014.000","5,265.000",12.000,279311,11.000,12.154,"177,745.000","192,564.366","1,498.000",85.000,"1,400.000",0.109,0.538,0.387,0.478,0.657,0.246,0.075,0.073,0.686,"31,860.000",0.170,0.669,"2,017.604","2,014.000","5,265.000",12.000
2,"58,952,159.000","Contact roll Airbag - , e-",177.600,A2,FI27837687A,"134,000.000",vw,golf,airbag,contact roll airbag,2026-02-03,2013,2020,7,"2,016.500",volkswagen,golf,original_valid,True,False,golf,86762,13.000,13.749,"186,801.000","195,467.968","1,395.000",81.000,"1,330.000",0.034,0.311,0.652,0.433,0.383,0.786,0.170,0.013,0.068,0.726,"31,860.000",0.170,0.669,"2,017.604","2,014.000","5,265.000",12.000,279311,11.000,12.154,"177,745.000","192,564.366","1,498.000",85.000,"1,400.000",0.109,0.538,0.387,0.478,0.657,0.246,0.075,0.073,0.686,"31,860.000",0.170,0.669,"2,017.604","2,014.000","5,265.000",12.000
3,"63,225,719.000","Contact roll Airbag - , e-",177.600,A2,FI27837687A,"253,000.000",vw,golf,airbag,contact roll airbag,2026-02-03,2013,2020,7,"2,016.500",volkswagen,golf,original_valid,True,False,golf,86762,13.000,13.749,"186,801.000","195,467.968","1,395.000",81.000,"1,330.000",0.034,0.311,0.652,0.433,0.383,0.786,0.170,0.013,0.068,0.726,"31,860.000",0.170,0.669,"2,017.604","2,014.000","5,265.000",12.000,279311,11.000,12.154,"177,745.000","192,564.366","1,498.000",85.000,"1,400.000",0.109,0.538,0.387,0.478,0.657,0.246,0.075,0.073,0.686,"31,860.000",0.170,0.669,"2,017.604","2,014.000","5,265.000",12.000
4,"64,336,640.000","Contact roll Airbag - , e-",177.600,A2,FI09389104A,"152,000.000",vw,golf,airbag,contact roll airbag,2026-02-03,2013,2020,7,"2,016.500",volkswagen,golf,original_valid,True,False,golf,86762,13.000,13.749,"186,801.000","195,467.968","1,395.000",81.000,"1,330.000",0.034,0.311,0.652,0.433,0.383,0.786,0.170,0.013,0.068,0.726,"31,860.000",0.170,0.669,"2,017.604","2,014.000","5,265.000",12.000,279311,11.000,12.154,"177,745.000","192,564.366","1,498.000",85.000,"1,400.000",0.109,0.538,0.387,0.478,0.657,0.246,0.075,0.073,0.686,"31,860.000",0.170,0.669,"2,017.604","2,014.000","5,265.000",12.000

## Initial Overview

This first overview checks dataset size, column names, and the starting data types before any cleaning changes are applied.

In [3]:
print("Original column names:")
print(df.columns.tolist())
print()

df.info()

Original column names:
['product_id', 'part_name', 'price', 'quality_grade', 'oem_number', 'mileage', 'brand', 'model', 'category', 'subcategory', 'scrape_date', 'year_start', 'year_end', 'year_span', 'year_mid', 'brand_merge_key', 'model_merge_key', 'repair_status', 'brand_is_known_model_family', 'model_looks_like_part_taxonomy', 'model_family_clean', 'model_total_registered', 'model_median_vehicle_age', 'model_mean_vehicle_age', 'model_median_mileage', 'model_mean_mileage', 'model_median_engine_cc', 'model_median_power_kw', 'model_median_mass_kg', 'model_share_of_market', 'model_share_within_brand', 'model_share_over_10y', 'model_share_over_200k_km', 'model_automatic_share', 'model_petrol_share', 'model_diesel_share', 'model_ev_share', 'model_hybrid_share', 'model_turbo_share', 'model_firstreg_total_2014_2026', 'model_firstreg_recent_share', 'model_firstreg_old_share', 'model_firstreg_weighted_year', 'model_firstreg_peak_year', 'model_firstreg_peak_count', 'model_firstreg_year_span', 'brand_total_registered', 'brand_median_vehicle_age', 'brand_mean_vehicle_age', 'brand_median_mileage', 'brand_mean_mileage', 'brand_median_engine_cc', 'brand_median_power_kw', 'brand_median_mass_kg', 'brand_share_of_market', 'brand_share_over_10y', 'brand_share_over_200k_km', 'brand_automatic_share', 'brand_petrol_share', 'brand_diesel_share', 'brand_ev_share', 'brand_hybrid_share', 'brand_turbo_share', 'brand_firstreg_total_2014_2026', 'brand_firstreg_recent_share', 'brand_firstreg_old_share', 'brand_firstreg_weighted_year', 'brand_firstreg_peak_year', 'brand_firstreg_peak_count', 'brand_firstreg_year_span']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11374 entries, 0 to 11373
Data columns (total 70 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   product_id                      11374 non-null  float64
 1   part_name                       11374 non-null  object
 2   price                           11374 non-null  float64
 3   quality_grade                   11374 non-null  object
 4   oem_number                      11374 non-null  object
 5   mileage                         10259 non-null  float64
 6   brand                           11374 non-null  object
 7   model                           11374 non-null  object
 8   category                        11374 non-null  object
 9   subcategory                     11374 non-null  object
 10  scrape_date                     11374 non-null  object
 11  year_start                      11374 non-null  int64
 12  year_end                        11374 non-null  int64
 13  year_span                       11374 non-null  int64
 14  year_mid                        11374 non-null  float64
 15  brand_merge_key                 11374 non-null  object
 16  model_merge_key                 11374 non-null  object
 17  repair_status                   11374 non-null  object
 18  brand_is_known_model_family     11374 non-null  bool
 19  model_looks_like_part_taxonomy  11374 non-null  bool
 20  model_family_clean              11374 non-null  object
 21  model_total_registered          11374 non-null  int64
 22  model_median_vehicle_age        11374 non-null  float64
 23  model_mean_vehicle_age          11374 non-null  float64
 24  model_median_mileage            11374 non-null  float64
 25  model_mean_mileage              11374 non-null  float64
 26  model_median_engine_cc          11374 non-null  float64
 27  model_median_power_kw           11374 non-null  float64
 28  model_median_mass_kg            11374 non-null  float64
 29  model_share_of_market           11374 non-null  float64
 30  model_share_within_brand        11374 non-null  float64
 31  model_share_over_10y            11374 non-null  float64
 32  model_share_over_200k_km        11374 non-null  float64
 33  model_automatic_share           11374 non-null  float64
 34  model_petrol_share              11374 non-null  float64
 35  model_diesel_share              11374 non-null  float64
 36  model_ev_share                  11374 non-null  float64
 37  model_hybrid_share              11374 non-null  float64
 38  model_turbo_share               11374 non-null  float64
 39  model_firstreg_total_2014_2026  11374 non-null  float64
 40  model_firstreg_recent_share     11374 non-null  float64
 41  model_firstreg_old_share        11374 non-null  float64
 42  model_firstreg_weighted_year    11374 non-null  float64
 43  model_firstreg_peak_year        11374 non-null  float64
 44  model_firstreg_peak_count       11374 non-null  float64
 45  model_firstreg_year_span        11374 non-null  float64
 46  brand_total_registered          11374 non-null  int64
 47  brand_median_vehicle_age        11374 non-null  float64
 48  brand_mean_vehicle_age          11374 non-null  float64
 49  brand_median_mileage            11374 non-null  float64
 50  brand_mean_mileage              11374 non-null  float64
 51  brand_median_engine_cc          11374 non-null  float64
 52  brand_median_power_kw           11374 non-null  float64
 53  brand_median_mass_kg            11374 non-null  float64
 54  brand_share_of_market           11374 non-null  float64
 55  brand_share_over_10y            11374 non-null  float64
 56  brand_share_over_200k_km        11374 non-null  float64
 57  brand_automatic_share           11374 non-null  float64
 58  brand_petrol_share              11374 non-null  float64
 59  brand_diesel_share              11374 non-null  float64
 60  brand_ev_share                  11374 non-null  float64
 61  brand_hybrid_share              11374 non-null  float64
 62  brand_turbo_share               11374 non-null  float64
 63  brand_firstreg_total_2014_2026  11374 non-null  float64
 64  brand_firstreg_recent_share     11374 non-null  float64
 65  brand_firstreg_old_share        11374 non-null  float64
 66  brand_firstreg_weighted_year    11374 non-null  float64
 67  brand_firstreg_peak_year        11374 non-null  float64
 68  brand_firstreg_peak_count       11374 non-null  float64
 69  brand_firstreg_year_span        11374 non-null  float64
dtypes: bool(2), float64(51), int64(5), object(12)
memory usage: 5.9+ MB

## Duplicate Observation Warning

Some observations that may look like duplicates can represent the **same listing or part observed repeatedly over time**. In this project, these repeated observations should be preserved unless there is a very clear accidental exact-duplicate issue.

For that reason, this notebook only **reports** duplicate patterns. It does **not** automatically drop duplicate rows.

## Basic Cleaning

The cleaning below is intentionally conservative. It standardizes names and obvious formatting issues without making modeling decisions or deleting information.

In [4]:
original_columns = df.columns.tolist()

# Standardize column names for easier handling.
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", "_", regex=True)
)

object_columns = df.select_dtypes(include=["object"]).columns.tolist()
for column in object_columns:
    df[column] = df[column].astype("string").str.strip()

# Replace empty strings with missing values after whitespace stripping.
df[object_columns] = df[object_columns].replace({"": pd.NA, "nan": pd.NA, "None": pd.NA})

numeric_name_fragments = [
    "price",
    "mileage",
    "year",
    "age",
    "registered",
    "engine_cc",
    "power_kw",
    "mass_kg",
    "share",
    "span",
    "mid",
]

candidate_numeric_columns = [
    column
    for column in df.columns
    if any(fragment in column for fragment in numeric_name_fragments)
    and column not in {"product_id"}
]

for column in candidate_numeric_columns:
    df[column] = pd.to_numeric(df[column], errors="coerce")

date_like_columns = [column for column in df.columns if "date" in column]
for column in date_like_columns:
    df[column] = pd.to_datetime(df[column], errors="coerce")

if "product_id" in df.columns:
    product_id_numeric = pd.to_numeric(df["product_id"], errors="coerce")
    df["product_id"] = product_id_numeric.astype("Int64").astype("string")

print("Column names before cleaning:")
print(original_columns)
print()
print("Column names after cleaning:")
print(df.columns.tolist())
print()
print(f"Object/string columns cleaned: {len(object_columns)}")
print(f"Numeric columns coerced where obvious: {len(candidate_numeric_columns)}")
print(f"Date-like columns parsed where obvious: {len(date_like_columns)}")

Column names before cleaning:
['product_id', 'part_name', 'price', 'quality_grade', 'oem_number', 'mileage', 'brand', 'model', 'category', 'subcategory', 'scrape_date', 'year_start', 'year_end', 'year_span', 'year_mid', 'brand_merge_key', 'model_merge_key', 'repair_status', 'brand_is_known_model_family', 'model_looks_like_part_taxonomy', 'model_family_clean', 'model_total_registered', 'model_median_vehicle_age', 'model_mean_vehicle_age', 'model_median_mileage', 'model_mean_mileage', 'model_median_engine_cc', 'model_median_power_kw', 'model_median_mass_kg', 'model_share_of_market', 'model_share_within_brand', 'model_share_over_10y', 'model_share_over_200k_km', 'model_automatic_share', 'model_petrol_share', 'model_diesel_share', 'model_ev_share', 'model_hybrid_share', 'model_turbo_share', 'model_firstreg_total_2014_2026', 'model_firstreg_recent_share', 'model_firstreg_old_share', 'model_firstreg_weighted_year', 'model_firstreg_peak_year', 'model_firstreg_peak_count', 'model_firstreg_year_span', 'brand_total_registered', 'brand_median_vehicle_age', 'brand_mean_vehicle_age', 'brand_median_mileage', 'brand_mean_mileage', 'brand_median_engine_cc', 'brand_median_power_kw', 'brand_median_mass_kg', 'brand_share_of_market', 'brand_share_over_10y', 'brand_share_over_200k_km', 'brand_automatic_share', 'brand_petrol_share', 'brand_diesel_share', 'brand_ev_share', 'brand_hybrid_share', 'brand_turbo_share', 'brand_firstreg_total_2014_2026', 'brand_firstreg_recent_share', 'brand_firstreg_old_share', 'brand_firstreg_weighted_year', 'brand_firstreg_peak_year', 'brand_firstreg_peak_count', 'brand_firstreg_year_span']

Column names after cleaning:
['product_id', 'part_name', 'price', 'quality_grade', 'oem_number', 'mileage', 'brand', 'model', 'category', 'subcategory', 'scrape_date', 'year_start', 'year_end', 'year_span', 'year_mid', 'brand_merge_key', 'model_merge_key', 'repair_status', 'brand_is_known_model_family', 'model_looks_like_part_taxonomy', 'model_family_clean', 'model_total_registered', 'model_median_vehicle_age', 'model_mean_vehicle_age', 'model_median_mileage', 'model_mean_mileage', 'model_median_engine_cc', 'model_median_power_kw', 'model_median_mass_kg', 'model_share_of_market', 'model_share_within_brand', 'model_share_over_10y', 'model_share_over_200k_km', 'model_automatic_share', 'model_petrol_share', 'model_diesel_share', 'model_ev_share', 'model_hybrid_share', 'model_turbo_share', 'model_firstreg_total_2014_2026', 'model_firstreg_recent_share', 'model_firstreg_old_share', 'model_firstreg_weighted_year', 'model_firstreg_peak_year', 'model_firstreg_peak_count', 'model_firstreg_year_span', 'brand_total_registered', 'brand_median_vehicle_age', 'brand_mean_vehicle_age', 'brand_median_mileage', 'brand_mean_mileage', 'brand_median_engine_cc', 'brand_median_power_kw', 'brand_median_mass_kg', 'brand_share_of_market', 'brand_share_over_10y', 'brand_share_over_200k_km', 'brand_automatic_share', 'brand_petrol_share', 'brand_diesel_share', 'brand_ev_share', 'brand_hybrid_share', 'brand_turbo_share', 'brand_firstreg_total_2014_2026', 'brand_firstreg_recent_share', 'brand_firstreg_old_share', 'brand_firstreg_weighted_year', 'brand_firstreg_peak_year', 'brand_firstreg_peak_count', 'brand_firstreg_year_span']

Object/string columns cleaned: 12
Numeric columns coerced where obvious: 51
Date-like columns parsed where obvious: 1

## Column Summary

A compact summary table helps identify the role and quality of each column. The conceptual column type is partly heuristic, so it should be treated as a review aid rather than a final classification.

In [5]:
def conceptual_column_type(series: pd.Series) -> str:
    column_name = series.name.lower()

    if column_name == "price":
        return "target"
    if column_name.endswith("_id") or column_name == "product_id":
        return "id"
    if pd.api.types.is_datetime64_any_dtype(series):
        return "date"
    if pd.api.types.is_numeric_dtype(series):
        return "numeric"
    if any(token in column_name for token in ["date", "time"]):
        return "date"
    if any(token in column_name for token in ["name", "description", "comment", "text", "number"]):
        return "text"
    if series.nunique(dropna=True) <= 30:
        return "categorical"
    return "text"


def sample_values(series: pd.Series, max_values: int = 5) -> str:
    values = series.dropna().astype(str).unique().tolist()[:max_values]
    return ", ".join(values)


column_summary = pd.DataFrame(
    {
        "column_name": df.columns,
        "dtype": [str(df[column].dtype) for column in df.columns],
        "conceptual_type": [conceptual_column_type(df[column]) for column in df.columns],
        "missing_count": [int(df[column].isna().sum()) for column in df.columns],
        "missing_percentage": [df[column].isna().mean() * 100 for column in df.columns],
        "unique_values": [int(df[column].nunique(dropna=True)) for column in df.columns],
        "sample_values": [sample_values(df[column]) for column in df.columns],
    }
).sort_values(["conceptual_type", "column_name"]).reset_index(drop=True)


display(column_summary)

,column_name,dtype,conceptual_type,missing_count,missing_percentage,unique_values,sample_values
0,brand,string,categorical,0,0.000,3,"vw, toyota, skoda"
1,brand_merge_key,string,categorical,0,0.000,3,"volkswagen, toyota, skoda"
2,category,string,categorical,0,0.000,7,"airbag, brakes, electric / transmitter / databox / sensor, engine, fuel"
3,model,string,categorical,0,0.000,3,"golf, corolla, octavia"
4,model_family_clean,string,categorical,0,0.000,3,"golf, corolla, octavia"
...,...,...,...,...,...,...,...
65,year_start,int64,numeric,0,0.000,16,"2013, 1992, 2004, 2020, 2009"
66,price,float64,target,0,0.000,1135,"177.6, 23.7, 17.8, 14.2, 473.6"
67,oem_number,string,text,0,0.000,54,"FI02042722A, FI05351686A, FI27837687A, FI09389104A, FI03986645A"
68,part_name,string,text,0,0.000,491,"Contact roll Airbag - , e-, Other airbags - , e-, Passenger airbag - , e-, Passenger airbag - , e-(Interior front), ..."
69,subcategory,string,text,0,0.000,137,"contact roll airbag, other airbags, passenger airbag, steering wheel airbag, left"

## Column-by-Column Inspection

The next cells inspect the dataset by column type. This is useful for spotting unusual ranges, unexpected values, and columns that may need more careful treatment later.

In [6]:
numeric_columns = df.select_dtypes(include=[np.number]).columns.tolist()

numeric_summary = pd.DataFrame(
    {
        "column_name": numeric_columns,
        "missing_count": [int(df[column].isna().sum()) for column in numeric_columns],
        "missing_percentage": [df[column].isna().mean() * 100 for column in numeric_columns],
        "min": [df[column].min() for column in numeric_columns],
        "max": [df[column].max() for column in numeric_columns],
        "mean": [df[column].mean() for column in numeric_columns],
        "median": [df[column].median() for column in numeric_columns],
    }
).sort_values("column_name")

print(f"Numeric columns: {len(numeric_columns)}")
display(numeric_summary)

Numeric columns: 55

,column_name,missing_count,missing_percentage,min,max,mean,median
42,brand_automatic_share,0,0.000,0.024,0.592,0.357,0.478
44,brand_diesel_share,0,0.000,0.069,0.269,0.192,0.246
45,brand_ev_share,0,0.000,0.005,0.075,0.048,0.067
50,brand_firstreg_old_share,0,0.000,0.102,0.669,0.441,0.572
53,brand_firstreg_peak_count,0,0.000,"5,265.000","5,868.000","5,502.930","5,395.000"
52,brand_firstreg_peak_year,0,0.000,"2,014.000","2,020.000","2,016.082","2,014.000"
49,brand_firstreg_recent_share,0,0.000,0.170,0.602,0.340,0.234
48,brand_firstreg_total_2014_2026,0,0.000,"31,860.000","48,859.000","38,432.164","35,135.000"
51,brand_firstreg_weighted_year,0,0.000,"2,017.604","2,021.013","2,018.966","2,018.163"
54,brand_firstreg_year_span,0,0.000,12.000,12.000,12.000,12.000
46,brand_hybrid_share,0,0.000,0.073,0.323,0.163,0.082
35,brand_mean_mileage,0,0.000,"179,263.663","193,594.446","188,668.733","192,564.366"
33,brand_mean_vehicle_age,0,0.000,9.062,13.211,11.532,12.154
36,brand_median_engine_cc,0,0.000,"1,498.000","1,598.000","1,532.702","1,498.000"
38,brand_median_mass_kg,0,0.000,"1,345.000","1,400.000","1,372.920","1,375.000"
34,brand_median_mileage,0,0.000,"162,500.000","179,335.500","173,422.127","177,745.000"
37,brand_median_power_kw,0,0.000,81.000,96.000,87.129,85.000
32,brand_median_vehicle_age,0,0.000,8.000,13.000,10.735,11.000
43,brand_petrol_share,0,0.000,0.630,0.925,0.741,0.657
39,brand_share_of_market,0,0.000,0.066,0.147,0.109,0.109
40,brand_share_over_10y,0,0.000,0.373,0.579,0.499,0.538
41,brand_share_over_200k_km,0,0.000,0.311,0.387,0.361,0.382
31,brand_total_registered,0,0.000,"170,359.000","377,068.000","278,395.619","279,311.000"
47,brand_turbo_share,0,0.000,0.084,0.831,0.523,0.686
1,mileage,1115,9.803,1.000,"919,294.000","144,787.159","120,000.000"
18,model_automatic_share,0,0.000,0.007,0.554,0.307,0.383
20,model_diesel_share,0,0.000,0.046,0.320,0.175,0.170
21,model_ev_share,0,0.000,0.000,0.013,0.004,0.000
26,model_firstreg_old_share,0,0.000,0.102,0.669,0.441,0.572
29,model_firstreg_peak_count,0,0.000,"5,265.000","5,868.000","5,502.930","5,395.000"
28,model_firstreg_peak_year,0,0.000,"2,014.000","2,020.000","2,016.082","2,014.000"
25,model_firstreg_recent_share,0,0.000,0.170,0.602,0.340,0.234
24,model_firstreg_total_2014_2026,0,0.000,"31,860.000","48,859.000","38,432.164","35,135.000"
27,model_firstreg_weighted_year,0,0.000,"2,017.604","2,021.013","2,018.966","2,018.163"
30,model_firstreg_year_span,0,0.000,12.000,12.000,12.000,12.000
22,model_hybrid_share,0,0.000,0.001,0.100,0.055,0.068
10,model_mean_mileage,0,0.000,"195,467.968","253,020.831","217,503.012","201,919.837"
8,model_mean_vehicle_age,0,0.000,10.602,22.448,15.761,13.749
11,model_median_engine_cc,0,0.000,"1,395.000","1,590.000","1,525.023","1,590.000"
13,model_median_mass_kg,0,0.000,"1,210.000","1,360.000","1,297.951","1,330.000"
9,model_median_mileage,0,0.000,"186,801.000","249,570.500","209,667.243","190,191.000"
12,model_median_power_kw,0,0.000,81.000,103.000,88.035,81.000
7,model_median_vehicle_age,0,0.000,10.000,21.000,14.817,13.000
19,model_petrol_share,0,0.000,0.617,0.954,0.790,0.786
14,model_share_of_market,0,0.000,0.023,0.034,0.030,0.032
16,model_share_over_10y,0,0.000,0.476,0.998,0.716,0.652
17,model_share_over_200k_km,0,0.000,0.427,0.710,0.527,0.433
15,model_share_within_brand,0,0.000,0.158,0.485,0.313,0.311
6,model_total_registered,0,0.000,"59,454.000","86,762.000","75,940.342","82,555.000"
23,model_turbo_share,0,0.000,0.045,0.913,0.549,0.726
0,price,0,0.000,5.900,"4,641.000",270.173,100.600
3,year_end,0,0.000,"1,987.000","2,027.000","2,015.555","2,020.000"
5,year_mid,0,0.000,"1,984.500","2,023.500","2,012.301","2,016.500"
4,year_span,0,0.000,3.000,15.000,6.507,7.000
2,year_start,0,0.000,"1,982.000","2,020.000","2,009.048","2,013.000"

In [7]:
categorical_columns = [
    column
    for column in df.columns
    if df[column].dtype in ["object", "string", "category", "boolean"]
]

print(f"Categorical/text-like columns selected for quick review: {len(categorical_columns)}")

for column in categorical_columns:
    print(f"\n--- {column} ---")
    print(f"Missing values: {df[column].isna().sum():,} ({df[column].isna().mean() * 100:.2f}%)")
    display(df[column].value_counts(dropna=False).head(10).rename("count").to_frame())

Categorical/text-like columns selected for quick review: 12

--- product_id ---
Missing values: 0 (0.00%)

            count
product_id
58830599        7
58830598        7
57894044        7
57182287        7
57180324        7
58830597        7
54363441        7
54360056        7
56933452        7
54480215        7

--- part_name ---
Missing values: 0 (0.00%)

                                          count
part_name
Suspension -(Rear)                          140
Shock absorbers rear -(Rear)                133
Drive shaft -(Left front)                   132
Trailing link rear -(Left)                  131
Curtain airbags -(Right)                    117
Trailing link rear -(Right)                 113
Drive shaft -(Right front)                  113
Hub rear -(Rear)                            108
Wheel bearing spindle shaft -(Left rear)    106
Curtain airbags -(Left)                      92

--- quality_grade ---
Missing values: 0 (0.00%)

               count
quality_grade
A2              9716
A1              1300
A3               178
B2               123
B1                18
c                 13
C2                 7
B3                 7
C1                 6
A                  6

--- oem_number ---
Missing values: 0 (0.00%)

             count
oem_number
FI27837687A   2188
FI10331575A   1038
FI09389104A   1000
FI06376738A    623
FI06292622A    575
FI09515254A    520
FI05028803A    520
FI05351686A    468
FI15710056A    466
FI03986645A    357

--- brand ---
Missing values: 0 (0.00%)

        count
brand
toyota   3947
vw       3790
skoda    3637

--- model ---
Missing values: 0 (0.00%)

         count
model
corolla   3947
golf      3790
octavia   3637

--- category ---
Missing values: 0 (0.00%)

                                           count
category
electric / transmitter / databox / sensor   2815
vehicle exterior / suspension               1826
engine                                      1786
gear box / drive axle / middle axle         1438
fuel                                        1389
brakes                                      1257
airbag                                       863

--- subcategory ---
Missing values: 0 (0.00%)

                 count
subcategory
all               1049
rear               332
right              297
left               278
right rear         255
left rear          249
right front        202
left front         202
either side        138
caliper bracket    102

--- brand_merge_key ---
Missing values: 0 (0.00%)

                 count
brand_merge_key
toyota            3947
volkswagen        3790
skoda             3637

--- model_merge_key ---
Missing values: 0 (0.00%)

                 count
model_merge_key
corolla           3947
golf              3790
octavia           3637

--- repair_status ---
Missing values: 0 (0.00%)

                count
repair_status
original_valid  11374

--- model_family_clean ---
Missing values: 0 (0.00%)

                    count
model_family_clean
corolla              3947
golf                 3790
octavia              3637

In [8]:
date_columns = [column for column in df.columns if pd.api.types.is_datetime64_any_dtype(df[column])]

if date_columns:
    date_summary = pd.DataFrame(
        {
            "column_name": date_columns,
            "missing_count": [int(df[column].isna().sum()) for column in date_columns],
            "missing_percentage": [df[column].isna().mean() * 100 for column in date_columns],
            "min_date": [df[column].min() for column in date_columns],
            "max_date": [df[column].max() for column in date_columns],
        }
    ).sort_values("column_name")
    display(date_summary)
else:
    print("No date columns were parsed successfully in the basic cleaning step.")

   column_name  missing_count  missing_percentage   min_date   max_date
0  scrape_date              0               0.000 2026-02-03 2026-02-18

## Duplicate Checks

These checks are purely diagnostic. They help assess whether there are exact row duplicates or repeated identifiers, but no rows are removed automatically.

In [9]:
full_row_duplicates = int(df.duplicated().sum())
print(f"Fully duplicated rows: {full_row_duplicates:,}")

id_columns = [column for column in df.columns if column.endswith("_id") or column == "product_id"]

if id_columns:
    duplicate_id_summary = pd.DataFrame(
        {
            "column_name": id_columns,
            "duplicate_values": [int(df[column].duplicated(keep=False).sum()) for column in id_columns],
            "unique_values": [int(df[column].nunique(dropna=True)) for column in id_columns],
            "missing_count": [int(df[column].isna().sum()) for column in id_columns],
        }
    ).sort_values("column_name")
    display(duplicate_id_summary)
else:
    print("No ID-like columns were detected.")

Fully duplicated rows: 0

  column_name  duplicate_values  unique_values  missing_count
0  product_id             10540           2619              0

## Missing Values Review

Missing values are reviewed after the basic cleaning step so that empty strings and parsing failures are already reflected in the totals.

In [10]:
missing_values_review = (
    pd.DataFrame(
        {
            "column_name": df.columns,
            "missing_count": [int(df[column].isna().sum()) for column in df.columns],
            "missing_percentage": [df[column].isna().mean() * 100 for column in df.columns],
        }
    )
    .sort_values(["missing_percentage", "missing_count"], ascending=[False, False])
    .reset_index(drop=True)
)

print("Columns with the highest missingness:")
display(missing_values_review.head(20))

Columns with the highest missingness:

                       column_name  missing_count  missing_percentage
0                          mileage           1115               9.803
1                       product_id              0               0.000
2                        part_name              0               0.000
3                            price              0               0.000
4                    quality_grade              0               0.000
5                       oem_number              0               0.000
6                            brand              0               0.000
7                            model              0               0.000
8                         category              0               0.000
9                      subcategory              0               0.000
10                     scrape_date              0               0.000
11                      year_start              0               0.000
12                        year_end              0               0.000
13                       year_span              0               0.000
14                        year_mid              0               0.000
15                 brand_merge_key              0               0.000
16                 model_merge_key              0               0.000
17                   repair_status              0               0.000
18     brand_is_known_model_family              0               0.000
19  model_looks_like_part_taxonomy              0               0.000

## Consistency Checks

The following quick checks are simple diagnostics for obvious structural issues in the cleaned dataset. They are kept separate from the main summary sections so the notebook remains easier to follow.

In [11]:
# Logical year consistency
((df["year_end"] < df["year_start"]).sum(), (df["year_span"] <= 0).sum())

(np.int64(0), np.int64(0))

## Mileage Review

Mileage deserves a closer look because it is one of the most practically important variables in the dataset and may contain unusually small values that require cautious handling.

In [12]:
# Mileage tail inspection
df["mileage"].quantile([0, 0.01, 0.05, 0.5, 0.95, 0.99, 1.0])

0.000         1.000
0.010     2,000.000
0.050    16,000.000
0.500   120,000.000
0.950   324,000.000
0.990   433,000.000
1.000   919,294.000
Name: mileage, dtype: float64

In [13]:
# Correlation quick look for numeric columns
numeric_df = df.select_dtypes(include=["number"])
numeric_df.corr(numeric_only=True)["price"].sort_values(ascending=False)

price                             1.000
year_mid                          0.226
year_end                          0.226
year_start                        0.224
year_span                         0.099
model_share_within_brand          0.023
model_diesel_share                0.022
model_hybrid_share                0.022
model_automatic_share             0.022
model_turbo_share                 0.022
model_median_mass_kg              0.022
brand_automatic_share             0.022
brand_turbo_share                 0.022
brand_median_power_kw             0.021
brand_diesel_share                0.021
brand_ev_share                    0.019
model_median_power_kw             0.019
model_share_of_market             0.019
model_total_registered            0.019
model_firstreg_old_share          0.018
brand_firstreg_old_share          0.018
brand_firstreg_total_2014_2026    0.016
model_firstreg_total_2014_2026    0.016
model_firstreg_peak_count         0.016
brand_firstreg_peak_count         0.016
brand_median_mass_kg              0.014
model_ev_share                    0.002
model_median_engine_cc           -0.002
brand_share_over_200k_km         -0.018
model_firstreg_weighted_year     -0.018
brand_firstreg_weighted_year     -0.018
brand_firstreg_recent_share      -0.019
model_firstreg_recent_share      -0.019
model_mean_mileage               -0.019
model_median_mileage             -0.020
brand_mean_mileage               -0.020
brand_hybrid_share               -0.020
brand_median_mileage             -0.020
model_firstreg_peak_year         -0.020
brand_firstreg_peak_year         -0.020
brand_median_engine_cc           -0.020
model_share_over_200k_km         -0.020
brand_petrol_share               -0.021
brand_share_over_10y             -0.021
brand_mean_vehicle_age           -0.021
model_mean_vehicle_age           -0.022
model_median_vehicle_age         -0.022
brand_median_vehicle_age         -0.022
model_share_over_10y             -0.022
brand_total_registered           -0.023
brand_share_of_market            -0.023
model_petrol_share               -0.023
mileage                          -0.098
model_firstreg_year_span            NaN
brand_firstreg_year_span            NaN
Name: price, dtype: float64

In [14]:
df.loc[df["mileage"] <= 1000, ["product_id", "part_name", "mileage", "brand", "model", "scrape_date"]]

,product_id,part_name,mileage,brand,model,scrape_date
122,65711229,"Adaptiv Farthållare Sensor - , e-","1,000.000",vw,golf,2026-02-03
154,54070103,"Other Control unit - , e-","1,000.000",vw,golf,2026-02-03
186,54410773,"Battery box / Fixing / Holder - , e-",1.000,vw,golf,2026-02-03
202,53919106,"Sensor ABS - , e-","1,000.000",vw,golf,2026-02-03
203,53919107,"Sensor ABS - , e-","1,000.000",vw,golf,2026-02-03
756,65711229,"Adaptiv Farthållare Sensor - , e-","1,000.000",vw,golf,2026-02-06
788,54070103,"Other Control unit - , e-","1,000.000",vw,golf,2026-02-06
820,54410773,"Battery box / Fixing / Holder - , e-",1.000,vw,golf,2026-02-06
836,53919106,"Sensor ABS - , e-","1,000.000",vw,golf,2026-02-06
837,53919107,"Sensor ABS - , e-","1,000.000",vw,golf,2026-02-06
1389,65711229,"Adaptiv Farthållare Sensor - , e-","1,000.000",vw,golf,2026-02-09
1421,54070103,"Other Control unit - , e-","1,000.000",vw,golf,2026-02-09
1453,54410773,"Battery box / Fixing / Holder - , e-",1.000,vw,golf,2026-02-09
1469,53919106,"Sensor ABS - , e-","1,000.000",vw,golf,2026-02-09
1470,53919107,"Sensor ABS - , e-","1,000.000",vw,golf,2026-02-09
2009,65711229,"Adaptiv Farthållare Sensor - , e-","1,000.000",vw,golf,2026-02-12
2041,54070103,"Other Control unit - , e-","1,000.000",vw,golf,2026-02-12
2073,54410773,"Battery box / Fixing / Holder - , e-",1.000,vw,golf,2026-02-12
2089,53919106,"Sensor ABS - , e-","1,000.000",vw,golf,2026-02-12
2090,53919107,"Sensor ABS - , e-","1,000.000",vw,golf,2026-02-12
2643,65711229,"Adaptiv Farthållare Sensor - , e-","1,000.000",vw,golf,2026-02-15
2706,54410773,"Battery box / Fixing / Holder - , e-",1.000,vw,golf,2026-02-15
2722,53919106,"Sensor ABS - , e-","1,000.000",vw,golf,2026-02-15
2723,53919107,"Sensor ABS - , e-","1,000.000",vw,golf,2026-02-15
3277,65711229,"Adaptiv Farthållare Sensor - , e-","1,000.000",vw,golf,2026-02-18
3309,54070103,"Other Control unit - , e-","1,000.000",vw,golf,2026-02-18
3341,54410773,"Battery box / Fixing / Holder - , e-",1.000,vw,golf,2026-02-18
3357,53919106,"Sensor ABS - , e-","1,000.000",vw,golf,2026-02-18
3358,53919107,"Sensor ABS - , e-","1,000.000",vw,golf,2026-02-18
4452,55488983,Caliper Bracket -(Left front),1.000,toyota,corolla,2026-02-03
4996,58730036,Shock absorbers rear -(Rear),1.000,toyota,corolla,2026-02-03
8268,54012565,Hub rear -(Rear),"1,000.000",skoda,octavia,2026-02-03
8270,54033359,Hub rear -(Rear),"1,000.000",skoda,octavia,2026-02-03
8308,54028811,Trailing link rear -(Right upper),"1,000.000",skoda,octavia,2026-02-03
8875,54012565,Hub rear -(Rear),"1,000.000",skoda,octavia,2026-02-06
8877,54033359,Hub rear -(Rear),"1,000.000",skoda,octavia,2026-02-06
8915,54028811,Trailing link rear -(Right upper),"1,000.000",skoda,octavia,2026-02-06
9477,54012565,Hub rear -(Rear),"1,000.000",skoda,octavia,2026-02-09
9479,54033359,Hub rear -(Rear),"1,000.000",skoda,octavia,2026-02-09
9517,54028811,Trailing link rear -(Right upper),"1,000.000",skoda,octavia,2026-02-09
10084,54012565,Hub rear -(Rear),"1,000.000",skoda,octavia,2026-02-12
10086,54033359,Hub rear -(Rear),"1,000.000",skoda,octavia,2026-02-12
10124,54028811,Trailing link rear -(Right upper),"1,000.000",skoda,octavia,2026-02-12
10691,54012565,Hub rear -(Rear),"1,000.000",skoda,octavia,2026-02-15
10693,54033359,Hub rear -(Rear),"1,000.000",skoda,octavia,2026-02-15
10731,54028811,Trailing link rear -(Right upper),"1,000.000",skoda,octavia,2026-02-15
11298,54012565,Hub rear -(Rear),"1,000.000",skoda,octavia,2026-02-18
11300,54033359,Hub rear -(Rear),"1,000.000",skoda,octavia,2026-02-18
11338,54028811,Trailing link rear -(Right upper),"1,000.000",skoda,octavia,2026-02-18

In [15]:
low_mileage_count = (df["mileage"] <= 1000).sum()
print(low_mileage_count)

49

In [16]:
# Replace implausibly low mileage values (<= 1000) with missing values
df.loc[df["mileage"] <= 1000, "mileage"] = np.nan

# Check updated mileage summary
print(df["mileage"].describe())

count    10,210.000
mean    145,478.007
std     101,862.971
min       2,000.000
25%      68,000.000
50%     121,000.000
75%     204,000.000
max     919,294.000
Name: mileage, dtype: float64

In [17]:
# Inspect very low mileage rows
print(df.loc[df["mileage"] <= 5000, ["product_id", "part_name", "mileage", "brand", "model", "scrape_date"]].sort_values("mileage"))

      product_id                               part_name   mileage   brand  \
494     54247541          Drive shaft - , e-(Left front) 2,000.000      vw
587     54254408  Trailing link rear - , e-(Right upper) 2,000.000      vw
1220    54254408  Trailing link rear - , e-(Right upper) 2,000.000      vw
1127    54247541          Drive shaft - , e-(Left front) 2,000.000      vw
1748    54247541          Drive shaft - , e-(Left front) 2,000.000      vw
...          ...                                     ...       ...     ...
9964    53489119                              Tank lid - 4,000.000   skoda
8755    53489119                              Tank lid - 4,000.000   skoda
9357    53489119                              Tank lid - 4,000.000   skoda
7458    53848511                       Engine Gasoline - 4,000.000  toyota
11179   53489119                              Tank lid - 4,000.000   skoda

         model scrape_date
494       golf  2026-02-03
587       golf  2026-02-03
1220      golf  2026-02-06
1127      golf  2026-02-06
1748      golf  2026-02-09
...        ...         ...
9964   octavia  2026-02-12
8755   octavia  2026-02-06
9357   octavia  2026-02-09
7458   corolla  2026-02-18
11179  octavia  2026-02-18

[134 rows x 6 columns]

In [18]:
# Low-end mileage frequency table up to 20,000
print(df.loc[df["mileage"] <= 20000, "mileage"].value_counts().sort_index())

mileage
2,000.000     79
2,334.000     18
3,000.000      6
4,000.000     31
6,000.000     12
7,000.000     59
8,000.000     32
10,000.000    42
11,000.000    66
12,000.000    60
15,000.000    37
16,000.000    72
17,000.000    56
18,000.000    62
19,000.000    30
20,000.000    88
Name: count, dtype: int64

In [19]:
# Summary counts by threshold
for threshold in [1000, 2000, 3000, 5000, 7000, 10000, 15000, 20000]:
    count = (df["mileage"] <= threshold).sum()
    print(f"<= {threshold}: {count}")

<= 1000: 0
<= 2000: 79
<= 3000: 103
<= 5000: 134
<= 7000: 205
<= 10000: 279
<= 15000: 442
<= 20000: 750

In [20]:
# Inspect rows in the suspicious low range
print(
    df.loc[
        df["mileage"].between(1001, 10000),
        ["product_id", "part_name", "mileage", "brand", "model", "scrape_date"]
    ].sort_values("mileage")
)

      product_id                                  part_name    mileage  \
11333   54242387                         Suspension -(Rear)  2,000.000
1220    54254408     Trailing link rear - , e-(Right upper)  2,000.000
1748    54247541             Drive shaft - , e-(Left front)  2,000.000
1840    54254408     Trailing link rear - , e-(Right upper)  2,000.000
10119   54242387                          Suspension-(Rear)  2,000.000
...          ...                                        ...        ...
7393    59245086                       Airbag krocksensor - 10,000.000
7179    59230183                         Suspension -(Rear) 10,000.000
7180    59230184                         Suspension -(Rear) 10,000.000
7394    59245089                       Airbag krocksensor - 10,000.000
7159    59241761  Wheel bearing spindle shaft -(Right rear) 10,000.000

        brand    model scrape_date
11333   skoda  octavia  2026-02-18
1220       vw     golf  2026-02-06
1748       vw     golf  2026-02-09
1840       vw     golf  2026-02-09
10119   skoda  octavia  2026-02-12
...       ...      ...         ...
7393   toyota  corolla  2026-02-18
7179   toyota  corolla  2026-02-15
7180   toyota  corolla  2026-02-15
7394   toyota  corolla  2026-02-18
7159   toyota  corolla  2026-02-15

[279 rows x 6 columns]

## Additional Formatting Cleanup

These final formatting adjustments standardize a small number of categorical text fields without changing the overall structure of the dataset.

In [21]:
# Standardize quality grade formatting
df["quality_grade"] = df["quality_grade"].astype("string").str.strip().str.upper()

# Check cleaned value counts
print(df["quality_grade"].value_counts(dropna=False))

quality_grade
A2    9716
A1    1300
A3     178
B2     123
B1      18
C       13
C2       7
B3       7
C1       6
A        6
Name: count, dtype: Int64

In [22]:
# Standardize subcategory text
df["subcategory"] = df["subcategory"].astype("string").str.strip().str.lower()

# Check cleaned value counts
print(df["subcategory"].value_counts(dropna=False).head(20))

subcategory
all                               1049
rear                               332
right                              297
left                               278
right rear                         255
left rear                          249
right front                        202
left front                         202
either side                        138
caliper bracket                    102
gear box 5 speed                   101
coil                               101
alternator                         101
passenger airbag                   101
contact roll airbag                100
steering wheel airbag              100
knee                               100
air purifier                       100
automatic gear                     100
fuse box / electricity central     100
Name: count, dtype: Int64

## Note on Subcategory

The `subcategory` field contains both true subtype labels and positional or location descriptors such as `left`, `rear`, and `right front`. It should therefore be interpreted as a mixed taxonomy field rather than a fully standardized part hierarchy.

## Validate newly added model lifecycle columns

Model-level lifecycle variables were merged from Traficom first-registration history. This section performs a lightweight post-merge validation to confirm that the new columns are present, missingness is expected, and the target model families have populated values.

In [23]:
# Check that expected lifecycle columns are present after the merge.
lifecycle_columns = [
    "model_firstreg_total_2014_2026",
    "model_firstreg_recent_share",
    "model_firstreg_old_share",
    "model_firstreg_weighted_year",
    "model_firstreg_peak_year",
    "model_firstreg_peak_count",
    "model_firstreg_year_span",
    "brand_firstreg_total_2014_2026",
    "brand_firstreg_recent_share",
    "brand_firstreg_old_share",
    "brand_firstreg_weighted_year",
    "brand_firstreg_peak_year",
    "brand_firstreg_peak_count",
    "brand_firstreg_year_span",
]

present_lifecycle_columns = [column for column in lifecycle_columns if column in df.columns]
missing_lifecycle_columns = [column for column in lifecycle_columns if column not in df.columns]

print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]:,}")
print("Present lifecycle columns:", present_lifecycle_columns)
print("Missing lifecycle columns:", missing_lifecycle_columns)

Rows: 11,374
Columns: 70
Present lifecycle columns: ['model_firstreg_total_2014_2026', 'model_firstreg_recent_share', 'model_firstreg_old_share', 'model_firstreg_weighted_year', 'model_firstreg_peak_year', 'model_firstreg_peak_count', 'model_firstreg_year_span', 'brand_firstreg_total_2014_2026', 'brand_firstreg_recent_share', 'brand_firstreg_old_share', 'brand_firstreg_weighted_year', 'brand_firstreg_peak_year', 'brand_firstreg_peak_count', 'brand_firstreg_year_span']
Missing lifecycle columns: []

In [24]:
# Summarize missingness in lifecycle columns.
if present_lifecycle_columns:
    lifecycle_missing_summary = pd.DataFrame({
        "missing_count": df[present_lifecycle_columns].isna().sum(),
        "missing_percentage": df[present_lifecycle_columns].isna().mean() * 100,
    })
    display(lifecycle_missing_summary)
else:
    print("No lifecycle columns available for missing-value summary.")

                                missing_count  missing_percentage
model_firstreg_total_2014_2026              0               0.000
model_firstreg_recent_share                 0               0.000
model_firstreg_old_share                    0               0.000
model_firstreg_weighted_year                0               0.000
model_firstreg_peak_year                    0               0.000
model_firstreg_peak_count                   0               0.000
model_firstreg_year_span                    0               0.000
brand_firstreg_total_2014_2026              0               0.000
brand_firstreg_recent_share                 0               0.000
brand_firstreg_old_share                    0               0.000
brand_firstreg_weighted_year                0               0.000
brand_firstreg_peak_year                    0               0.000
brand_firstreg_peak_count                   0               0.000
brand_firstreg_year_span                    0               0.000

In [25]:
# Preview lifecycle values for target model families.
target_model_values = ["golf", "corolla", "octavia"]
target_key_column = "model_family_clean" if "model_family_clean" in df.columns else "model"
target_preview_columns = [
    column
    for column in ["brand", "model", "model_family_clean"] + lifecycle_columns
    if column in df.columns
]

target_lifecycle_preview = (
    df.loc[df[target_key_column].isin(target_model_values), target_preview_columns]
    .drop_duplicates()
    .sort_values([column for column in ["brand", target_key_column] if column in target_preview_columns])
)

display(target_lifecycle_preview.head(20))

,brand,model,model_family_clean,model_firstreg_total_2014_2026,model_firstreg_recent_share,model_firstreg_old_share,model_firstreg_weighted_year,model_firstreg_peak_year,model_firstreg_peak_count,model_firstreg_year_span,brand_firstreg_total_2014_2026,brand_firstreg_recent_share,brand_firstreg_old_share,brand_firstreg_weighted_year,brand_firstreg_peak_year,brand_firstreg_peak_count,brand_firstreg_year_span
7737,skoda,octavia,octavia,"48,859.000",0.234,0.572,"2,018.163","2,014.000","5,868.000",12.000,"48,859.000",0.234,0.572,"2,018.163","2,014.000","5,868.000",12.000
3790,toyota,corolla,corolla,"35,135.000",0.602,0.102,"2,021.013","2,020.000","5,395.000",12.000,"35,135.000",0.602,0.102,"2,021.013","2,020.000","5,395.000",12.000
0,vw,golf,golf,"31,860.000",0.170,0.669,"2,017.604","2,014.000","5,265.000",12.000,"31,860.000",0.170,0.669,"2,017.604","2,014.000","5,265.000",12.000

In [26]:
# Confirm this validation section has not changed the number of price rows.
print(f"Raw merged rows: {df_raw.shape[0]:,}")
print(f"Current rows: {df.shape[0]:,}")
print("Lifecycle validation is diagnostic only; it should not change the number of price rows.")

Raw merged rows: 11,374
Current rows: 11,374
Lifecycle validation is diagnostic only; it should not change the number of price rows.

## Add Listing-History Features

These exploratory listing-history variables summarize how often each `product_id` appears in the sampled marketplace window and whether its observed listing price changed across scrape dates. They are computed from repeated marketplace observations in the cleaned dataframe and merged back before saving the final clean master dataset.

In [27]:
# Check required columns and parse scrape_date for listing-history features.
listing_history_required_columns = ["product_id", "scrape_date", "price"]
missing_listing_history_columns = [
    column for column in listing_history_required_columns if column not in df.columns
]

if missing_listing_history_columns:
    print(f"Cannot create listing-history features. Missing columns: {missing_listing_history_columns}")
    can_build_listing_history = False
else:
    can_build_listing_history = True
    df["scrape_date"] = pd.to_datetime(df["scrape_date"], errors="coerce")
    print("Required listing-history columns are present.")
    print(f"Unparseable scrape_date values: {df['scrape_date'].isna().sum():,}")

Required listing-history columns are present.
Unparseable scrape_date values: 0

In [28]:
# Engineer product-level listing-history variables on the full cleaned dataframe.
listing_history_columns = [
    "times_observed",
    "first_seen_date",
    "last_seen_date",
    "observed_span_days",
    "price_changed_flag",
    "price_change_count",
    "absolute_price_change",
    "relative_price_change_pct",
]

def count_price_changes(values):
    prices = values.dropna()
    if len(prices) <= 1:
        return 0
    return int(prices.ne(prices.shift()).iloc[1:].sum())

def first_non_null(values):
    values = values.dropna()
    return values.iloc[0] if len(values) else np.nan

def last_non_null(values):
    values = values.dropna()
    return values.iloc[-1] if len(values) else np.nan

if can_build_listing_history:
    listing_history_shape_before = df.shape
    listing_history_work = df[["product_id", "scrape_date", "price"]].copy()
    listing_history_work["price"] = pd.to_numeric(listing_history_work["price"], errors="coerce")
    listing_history_work["_row_order"] = np.arange(len(listing_history_work))
    listing_history_work = listing_history_work.sort_values(
        ["product_id", "scrape_date", "_row_order"],
        kind="mergesort",
        na_position="last",
    )

    listing_history_features = listing_history_work.groupby("product_id", as_index=False).agg(
        times_observed=("product_id", "size"),
        first_seen_date=("scrape_date", "min"),
        last_seen_date=("scrape_date", "max"),
        price_changed_flag=("price", lambda values: int(values.nunique(dropna=True) > 1)),
        price_change_count=("price", count_price_changes),
        first_observed_price=("price", first_non_null),
        last_observed_price=("price", last_non_null),
    )

    listing_history_features["observed_span_days"] = (
        listing_history_features["last_seen_date"] - listing_history_features["first_seen_date"]
    ).dt.days
    listing_history_features["absolute_price_change"] = (
        listing_history_features["last_observed_price"] - listing_history_features["first_observed_price"]
    )
    listing_history_features["relative_price_change_pct"] = np.where(
        listing_history_features["first_observed_price"].notna()
        & listing_history_features["first_observed_price"].ne(0),
        listing_history_features["absolute_price_change"] / listing_history_features["first_observed_price"] * 100,
        np.nan,
    )

    listing_history_features = listing_history_features[["product_id"] + listing_history_columns]

    print(f"Dataframe shape before listing-history merge: {listing_history_shape_before}")
    print("New listing-history columns:", listing_history_columns)
    display(listing_history_features.head())
else:
    listing_history_features = pd.DataFrame(columns=["product_id"] + listing_history_columns)

Dataframe shape before listing-history merge: (11374, 70)
New listing-history columns: ['times_observed', 'first_seen_date', 'last_seen_date', 'observed_span_days', 'price_changed_flag', 'price_change_count', 'absolute_price_change', 'relative_price_change_pct']

,product_id,times_observed,first_seen_date,last_seen_date,observed_span_days,price_changed_flag,price_change_count,absolute_price_change,relative_price_change_pct
0,53365006,1,2026-02-03,2026-02-03,0,0,0,0.000,0.000
1,53365016,1,2026-02-03,2026-02-03,0,0,0,0.000,0.000
2,53365106,6,2026-02-03,2026-02-18,15,1,5,-1.000,-0.111
3,53366348,6,2026-02-03,2026-02-18,15,1,4,-0.100,-0.211
4,53367213,6,2026-02-03,2026-02-18,15,1,5,-0.400,-0.109

In [29]:
# Merge listing-history variables back and validate the result.
if can_build_listing_history:
    existing_listing_history_columns = [column for column in listing_history_columns if column in df.columns]
    if existing_listing_history_columns:
        df = df.drop(columns=existing_listing_history_columns)

    rows_before_listing_history_merge = len(df)
    df = df.merge(listing_history_features, on="product_id", how="left", validate="many_to_one")

    print(f"Dataframe shape before listing-history merge: {listing_history_shape_before}")
    print(f"Dataframe shape after listing-history merge: {df.shape}")
    print("Newly added columns:", listing_history_columns)

    if len(df) == rows_before_listing_history_merge:
        print("Row count unchanged after listing-history merge.")
    else:
        print("Warning: row count changed after listing-history merge.")

    print("Null counts for listing-history columns:")
    display(df[listing_history_columns].isna().sum().to_frame("null_count"))

    print("Summary for listing-history count/span columns:")
    display(df[["times_observed", "observed_span_days", "price_change_count"]].describe())

    print("price_changed_flag value counts:")
    display(df["price_changed_flag"].value_counts(dropna=False).to_frame("count"))

    repeated_product_ids = df.loc[df["times_observed"] > 1, "product_id"].drop_duplicates().head(5)
    sample_columns = ["product_id", "scrape_date", "price"] + listing_history_columns
    print("Sample repeated product_id cases:")
    display(
        df.loc[df["product_id"].isin(repeated_product_ids), sample_columns]
        .sort_values(["product_id", "scrape_date"], kind="mergesort")
        .head(30)
    )

    print("Extreme relative_price_change_pct values:")
    display(df["relative_price_change_pct"].describe())
    display(
        df[["product_id", "relative_price_change_pct"]]
        .drop_duplicates()
        .sort_values("relative_price_change_pct")
        .head(5)
    )
    display(
        df[["product_id", "relative_price_change_pct"]]
        .drop_duplicates()
        .sort_values("relative_price_change_pct", ascending=False)
        .head(5)
    )

Dataframe shape before listing-history merge: (11374, 70)
Dataframe shape after listing-history merge: (11374, 78)
Newly added columns: ['times_observed', 'first_seen_date', 'last_seen_date', 'observed_span_days', 'price_changed_flag', 'price_change_count', 'absolute_price_change', 'relative_price_change_pct']
Row count unchanged after listing-history merge.
Null counts for listing-history columns:

                           null_count
times_observed                      0
first_seen_date                     0
last_seen_date                      0
observed_span_days                  0
price_changed_flag                  0
price_change_count                  0
absolute_price_change               0
relative_price_change_pct           0

Summary for listing-history count/span columns:

       times_observed  observed_span_days  price_change_count
count      11,374.000          11,374.000          11,374.000
mean            5.596              13.760               3.908
std             1.360               3.999               1.383
min             1.000               0.000               0.000
25%             6.000              15.000               3.000
50%             6.000              15.000               4.000
75%             6.000              15.000               5.000
max             7.000              15.000               5.000

price_changed_flag value counts:

                    count
price_changed_flag
1                   10503
0                     871

Sample repeated product_id cases:

,product_id,scrape_date,price,times_observed,first_seen_date,last_seen_date,observed_span_days,price_changed_flag,price_change_count,absolute_price_change,relative_price_change_pct
5,54655558,2026-02-03,23.700,6,2026-02-03,2026-02-18,15,1,3,0.000,0.000
639,54655558,2026-02-06,23.600,6,2026-02-03,2026-02-18,15,1,3,0.000,0.000
1272,54655558,2026-02-09,23.600,6,2026-02-03,2026-02-18,15,1,3,0.000,0.000
1892,54655558,2026-02-12,23.800,6,2026-02-03,2026-02-18,15,1,3,0.000,0.000
2526,54655558,2026-02-15,23.700,6,2026-02-03,2026-02-18,15,1,3,0.000,0.000
3160,54655558,2026-02-18,23.700,6,2026-02-03,2026-02-18,15,1,3,0.000,0.000
2,58952159,2026-02-03,177.600,6,2026-02-03,2026-02-18,15,1,5,-0.200,-0.113
635,58952159,2026-02-06,177.000,6,2026-02-03,2026-02-18,15,1,5,-0.200,-0.113
1268,58952159,2026-02-09,176.900,6,2026-02-03,2026-02-18,15,1,5,-0.200,-0.113
1889,58952159,2026-02-12,178.500,6,2026-02-03,2026-02-18,15,1,5,-0.200,-0.113
2523,58952159,2026-02-15,177.900,6,2026-02-03,2026-02-18,15,1,5,-0.200,-0.113
3157,58952159,2026-02-18,177.400,6,2026-02-03,2026-02-18,15,1,5,-0.200,-0.113
0,63136980,2026-02-03,177.600,4,2026-02-03,2026-02-18,15,1,3,-0.200,-0.113
1887,63136980,2026-02-12,178.500,4,2026-02-03,2026-02-18,15,1,3,-0.200,-0.113
2521,63136980,2026-02-15,177.900,4,2026-02-03,2026-02-18,15,1,3,-0.200,-0.113
3155,63136980,2026-02-18,177.400,4,2026-02-03,2026-02-18,15,1,3,-0.200,-0.113
3,63225719,2026-02-03,177.600,6,2026-02-03,2026-02-18,15,1,5,-0.200,-0.113
636,63225719,2026-02-06,177.000,6,2026-02-03,2026-02-18,15,1,5,-0.200,-0.113
1269,63225719,2026-02-09,176.900,6,2026-02-03,2026-02-18,15,1,5,-0.200,-0.113
1890,63225719,2026-02-12,178.500,6,2026-02-03,2026-02-18,15,1,5,-0.200,-0.113
2524,63225719,2026-02-15,177.900,6,2026-02-03,2026-02-18,15,1,5,-0.200,-0.113
3158,63225719,2026-02-18,177.400,6,2026-02-03,2026-02-18,15,1,5,-0.200,-0.113
1,64390201,2026-02-03,177.600,6,2026-02-03,2026-02-18,15,1,5,-0.200,-0.113
634,64390201,2026-02-06,177.000,6,2026-02-03,2026-02-18,15,1,5,-0.200,-0.113
1267,64390201,2026-02-09,176.900,6,2026-02-03,2026-02-18,15,1,5,-0.200,-0.113
1888,64390201,2026-02-12,178.500,6,2026-02-03,2026-02-18,15,1,5,-0.200,-0.113
2522,64390201,2026-02-15,177.900,6,2026-02-03,2026-02-18,15,1,5,-0.200,-0.113
3156,64390201,2026-02-18,177.400,6,2026-02-03,2026-02-18,15,1,5,-0.200,-0.113

Extreme relative_price_change_pct values:

count   11,374.000
mean        -0.035
std          0.703
min        -29.899
25%         -0.121
50%          0.000
75%          0.115
max          0.847
Name: relative_price_change_pct, dtype: float64

     product_id  relative_price_change_pct
7869   62801577                    -29.899
9945   66697123                     -0.663
1938   54223147                     -0.636
1896   54440014                     -0.630
2174   54054788                     -0.621

     product_id  relative_price_change_pct
3857   54491283                      0.847
3856   54483257                      0.847
7816   54094531                      0.847
7817   54099834                      0.847
7814   53785897                      0.847

## Save Cleaned Dataset

The file saved here is the final cleaned master dataset for later splitting and modeling. It includes conservative formatting/type fixes, Traficom lifecycle variables, and the listing-history features added above.

In [30]:
output_path = Path("/Users/riteshbhandari/Documents/Dokumentit – Ritesh - MacBook Pro/GitHub/DPPM/datasets/cleaned/clean_master_dataset.csv")
output_path.parent.mkdir(parents=True, exist_ok=True)

df.to_csv(output_path, index=False)
print(f"Clean master dataset saved to: {output_path}")

Clean master dataset saved to: /Users/riteshbhandari/Documents/Dokumentit – Ritesh - MacBook Pro/GitHub/DPPM/datasets/cleaned/clean_master_dataset.csv