# Preprocessing Corolla

## Preprocessing Plan

We follow the same preprocessing steps for this brand dataset.

In [28]:
# Step 1: Load merged brand CSV into a DataFrame
# Step 2: Check shape, columns, dtypes, and missing values
# Step 3: Standardize column names and text formatting
# Step 4: Convert numeric fields (price, mileage) to proper numeric types
# Step 5: Parse year/scrape date fields and clean invalid values
# Step 6: Handle missing values with explicit rules
# Step 7: Remove duplicates (exact rows + key-based duplicates)
# Step 8: Detect and cap/remove clear outliers where needed
# Step 9: Create modeling-ready features and keep target variable clean
# Step 10: Save cleaned dataset to datasets/processed/

In [29]:
import pandas as pd

In [30]:
df_corolla = pd.read_csv("/Users/riteshbhandari/Documents/Dokumentit – Ritesh - MacBook Pro/GitHub/DPPM/datasets/merged/dppm_toyota_corolla_yaris.csv")

In [31]:
df_corolla.head()

,product_id,part_name,price,quality_grade,year,oem_number,engine_code,mileage,brand,model,category,subcategory,scrape_date,scrape_timestamp
0,63019913.0,Contact roll Airbag to,238.4,NaN,2019-2027,FI09389104A,2ZRFXE,NaN,Toyota,Corolla,Airbag,Contact roll Airbag,2026-02-01,NaN
1,63126049.0,Contact roll Airbag to,226.5,NaN,2019-2027,FI24637030A,NaN,NaN,Toyota,Corolla,Airbag,Contact roll Airbag,2026-02-01,NaN
2,61076273.0,Contact roll Airbag to,214.5,NaN,2019-2027,FI27837687A,2ZRFXE,NaN,Toyota,Corolla,Airbag,Contact roll Airbag,2026-02-01,NaN
3,63099984.0,Contact roll Airbag to,226.5,NaN,2008-2012,FI22893129A,1ZRFE,NaN,Toyota,Corolla,Airbag,Contact roll Airbag,2026-02-01,NaN
4,65759035.0,Contact roll Airbag to,202.6,NaN,2002-2007,FI06018105A,NaN,NaN,Toyota,Corolla,Airbag,Contact roll Airbag,2026-02-01,NaN

In [32]:
df_corolla.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7435 entries, 0 to 7434
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product_id        5920 non-null   float64
 1   part_name         7435 non-null   object
 2   price             7433 non-null   float64
 3   quality_grade     7403 non-null   object
 4   year              7433 non-null   object
 5   oem_number        6531 non-null   object
 6   engine_code       4840 non-null   object
 7   mileage           5265 non-null   float64
 8   brand             7435 non-null   object
 9   model             7435 non-null   object
 10  category          7435 non-null   object
 11  subcategory       7435 non-null   object
 12  scrape_date       5867 non-null   object
 13  scrape_timestamp  5303 non-null   object
dtypes: float64(3), object(11)
memory usage: 813.3+ KB

In [33]:
df_corolla.isna().sum()

product_id          1515
part_name              0
price                  2
quality_grade         32
year                   2
oem_number           904
engine_code         2595
mileage             2170
brand                  0
model                  0
category               0
subcategory            0
scrape_date         1568
scrape_timestamp    2132
dtype: int64

In [34]:
# deleting not needed columns
df_corolla = df_corolla.drop(columns=['engine_code'])
df_corolla = df_corolla.drop(columns=['scrape_timestamp'])
print(df_corolla.shape)

(7435, 12)

In [35]:
# price column analysis

df_corolla['price'].dtype
df_corolla['price'].head()

0    238.4
1    226.5
2    214.5
3    226.5
4    202.6
Name: price, dtype: float64

In [36]:
# drop missing prices
df_corolla = df_corolla.dropna(subset=['price'])
print(df_corolla.shape)
print(df_corolla["price"].describe())

(7433, 12)
count    7433.000000
mean      251.894793
std       520.143383
min         5.000000
25%        47.400000
50%        94.700000
75%       226.100000
max      3689.000000
Name: price, dtype: float64

In [37]:
# Year column analysis
print(df_corolla['year'].dtype)
print(df_corolla['year'].head())
print(df_corolla['year'].describe())
print(df_corolla['year'].unique())

object
0    2019-2027
1    2019-2027
2    2019-2027
3    2008-2012
4    2002-2007
Name: year, dtype: object
count          7433
unique           12
top       2019-2027
freq           2606
Name: year, dtype: object
['2019-2027' '2008-2012' '2002-2007' '2013-2018' '1998-2001' '1993-1997'
 '1983-1987' '1988-1992' '1982-1987' '2020-2027' '2015-2020' '2012-2014']

In [38]:
# splitting year data to end start and width of compatibility
df_corolla[['year_start', 'year_end']] = df_corolla['year'].str.split('-', expand=True)

df_corolla['year_start'] = pd.to_numeric(df_corolla['year_start'], errors='coerce')
df_corolla['year_end'] = pd.to_numeric(df_corolla['year_end'], errors='coerce')

df_corolla['year_span'] = df_corolla['year_end'] - df_corolla['year_start']
df_corolla['year_mid'] = (df_corolla['year_start'] + df_corolla['year_end']) / 2

print(df_corolla[['year','year_start', 'year_end', 'year_span', 'year_mid']].head())

        year  year_start  year_end  year_span  year_mid
0  2019-2027        2019      2027          8    2023.0
1  2019-2027        2019      2027          8    2023.0
2  2019-2027        2019      2027          8    2023.0
3  2008-2012        2008      2012          4    2010.0
4  2002-2007        2002      2007          5    2004.5

In [39]:
df_corolla

,product_id,part_name,price,quality_grade,year,oem_number,mileage,brand,model,category,subcategory,scrape_date,year_start,year_end,year_span,year_mid
0,63019913.0,Contact roll Airbag to,238.4,NaN,2019-2027,FI09389104A,NaN,Toyota,Corolla,Airbag,Contact roll Airbag,2026-02-01,2019,2027,8,2023.0
1,63126049.0,Contact roll Airbag to,226.5,NaN,2019-2027,FI24637030A,NaN,Toyota,Corolla,Airbag,Contact roll Airbag,2026-02-01,2019,2027,8,2023.0
2,61076273.0,Contact roll Airbag to,214.5,NaN,2019-2027,FI27837687A,NaN,Toyota,Corolla,Airbag,Contact roll Airbag,2026-02-01,2019,2027,8,2023.0
3,63099984.0,Contact roll Airbag to,226.5,NaN,2008-2012,FI22893129A,NaN,Toyota,Corolla,Airbag,Contact roll Airbag,2026-02-01,2008,2012,4,2010.0
4,65759035.0,Contact roll Airbag to,202.6,NaN,2002-2007,FI06018105A,NaN,Toyota,Corolla,Airbag,Contact roll Airbag,2026-02-01,2002,2007,5,2004.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7430,60991939.0,ABS Hydraulikoneisto XP130,500.0,A1,2015-2020,4705052480ALKUPER,54000.0,Toyota,Yaris,Jarrut,ABS Hydraulikoneisto,NaN,2015,2020,5,2017.5
7431,54210461.0,ABS Hydraulikoneisto XP130,474.0,A1,2015-2020,H14J3020417AALKUPER,10000.0,Toyota,Yaris,Jarrut,ABS Hydraulikoneisto,NaN,2015,2020,5,2017.5
7432,54429526.0,ABS Hydraulikoneisto XP130,500.0,A2,2012-2014,44540-0D020,44000.0,Toyota,Yaris,Jarrut,ABS Hydraulikoneisto,NaN,2012,2014,2,2013.0
7433,59857278.0,ABS Hydraulikoneisto XP21,500.0,A2,2020-2027,44540-K0140ALKUPER,48000.0,Toyota,Yaris,Jarrut,ABS Hydraulikoneisto,NaN,2020,2027,7,2023.5
7434,62936015.0,ABS Hydraulikoneisto XP21,489.2,A1,2020-2027,440500DG30ALKUPER,25000.0,Toyota,Yaris,Jarrut,ABS Hydraulikoneisto,NaN,2020,2027,7,2023.5